name: my_calendar_tg_bot_dart
description: Calendar Telegram Bot
version: 1.0.0

environment:
  sdk: ^3.7.3

dependencies:
  dotenv: ^4.2.0
  televerse: ^2.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
